CREATE DATABASE BUSSYS;

CREATE TABLE ONIBUS(
    IDONIBUS SERIAL PRIMARY KEY NOT NULL,
    PLACA VARCHAR(30) NOT NULL,
    MODELO VARCHAR(30) NOT NULL
);

CREATE TABLE EMPRESA(
    IDEMPRESA SERIAL PRIMARY KEY NOT NULL,
    CNPJ VARCHAR(18) NOT NULL,
    CAIXA REAL NOT NULL,
    ENDERECO VARCHAR(255) NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    ID_ONIBUS INT NOT NULL,
    FOREIGN KEY (ID_ONIBUS) REFERENCES ONIBUS (IDONIBUS)
);

CREATE TABLE VIAGEM(
    IDVIAGEM SERIAL PRIMARY KEY NOT NULL,
    HORA_IN CHAR(5) NOT NULL,
    HORA_FIN CHAR(5) NOT NULL,
    DIST_PERCORRIDA REAL NOT NULL,
    ID_ONIBUS INT NOT NULL,
    FOREIGN KEY (ID_ONIBUS) REFERENCES ONIBUS (IDONIBUS)
);

CREATE TABLE MOTORISTA(
    IDMOTORISTA SERIAL PRIMARY KEY NOT NULL,
    CPF VARCHAR(14) NOT NULL,
    IDADE INT NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    DATA_NASC VARCHAR(10) NOT NULL,
    ID_VIAGEM INT NOT NULL,
    FOREIGN KEY (ID_VIAGEM) REFERENCES VIAGEM (IDVIAGEM)
);

CREATE TABLE PASSAGEM(
    IDPASSAGEM SERIAL PRIMARY KEY NOT NULL,
    VALOR DOUBLE PRECISION NOT NULL,
    DATA_COMPRA VARCHAR(30) NOT NULL,
    ID_ONIBUS INT NOT NULL,
    FOREIGN KEY (ID_ONIBUS) REFERENCES ONIBUS (IDONIBUS)
);

CREATE TABLE PASSAGEIRO(
    IDPASSAGEIRO SERIAL PRIMARY KEY NOT NULL,
    NUMERO_CARTAO INT NOT NULL UNIQUE,
    NOME VARCHAR(30) NOT NULL,
    ID_PASSAGEGEM INT NOT NULL,
    FOREIGN KEY (ID_PASSAGEGEM) REFERENCES PASSAGEM (IDPASSAGEM)
);

CREATE TABLE LINHA(
    IDLINHA SERIAL PRIMARY KEY NOT NULL,
    ORIGEM VARCHAR(30) NOT NULL,
    DESTINO VARCHAR(30) NOT NULL,
    ID_ONIBUS INT NOT NULL,
    FOREIGN KEY (ID_ONIBUS) REFERENCES ONIBUS (IDONIBUS)
);

CREATE TABLE ROTA(
    IDROTA SERIAL PRIMARY KEY NOT NULL,
    NOME VARCHAR(30) NOT NULL,
    ID_LINHA INT NOT NULL UNIQUE,
    FOREIGN KEY (ID_LINHA) REFERENCES LINHA (IDLINHA)
);

INSERT INTO ONIBUS (PLACA, MODELO) VALUES('ASD456A','23423FFFFS');
INSERT INTO ONIBUS (PLACA, MODELO) VALUES('SASAS5','435ASFF123');
INSERT INTO ONIBUS (PLACA, MODELO) VALUES('AS4S4W','2245554AAA');

INSERT INTO PASSAGEM (VALOR, DATA_COMPRA, ID_ONIBUS) VALUES(7.9,'28/02/2022', 1);
INSERT INTO PASSAGEM (VALOR, DATA_COMPRA, ID_ONIBUS) VALUES(8.5,'01/03/2022', 2);
INSERT INTO PASSAGEM (VALOR, DATA_COMPRA, ID_ONIBUS) VALUES(10,'02/03/2022', 1);

INSERT INTO PASSAGEIRO (NUMERO_CARTAO, NOME, ID_PASSAGEGEM) VALUES(48948944, 'PEDRO', 1);
INSERT INTO PASSAGEIRO (NUMERO_CARTAO, NOME, ID_PASSAGEGEM) VALUES(18944256, 'RONALDO', 3);
INSERT INTO PASSAGEIRO (NUMERO_CARTAO, NOME, ID_PASSAGEGEM) VALUES(95148723, 'GABRIEL', 2);

INSERT INTO LINHA (ORIGEM, DESTINO, ID_ONIBUS) VALUES('VILA LAURA', 'COMERCIO', 1);
INSERT INTO LINHA (ORIGEM, DESTINO, ID_ONIBUS) VALUES('ITAGARA', 'C. DAS ARVORES', 2);

INSERT INTO ROTA (NOME, ID_LINHA) VALUES('ALIOMAR BALEEIRO', 1);
INSERT INTO ROTA (NOME, ID_LINHA) VALUES('COMERCIO', 2);

INSERT INTO EMPRESA (CNPJ, CAIXA, ENDERECO, NOME, ID_ONIBUS) VALUES 
('00112112000139', 100.543,'RUA PADRE MEU BOI', 'FARIA', 1),
('31479752417859', 900.993,'RUA JOSE FARIA DE LIMA', 'INTEGRA', 2),
('75287527997415', 876.987, 'RUA PEDRO ABRANTE DE JESUS', 'CSR DO METRO', 3);

INSERT INTO VIAGEM (HORA_IN, HORA_FIN, DIST_PERCORRIDA, ID_ONIBUS) VALUES
('13:45', '19:00', 48.55, 1),
('14:20', '18:02', 33.32, 2),
('12:24', '16:03', 50.21, 3);

INSERT INTO MOTORISTA (CPF, IDADE, NOME, DATA_NASC, ID_VIAGEM) VALUES
('45659174166', 32, 'JOSE PEDRO FAUSTO', '25/04/1990', 1),
('78944512368', 29, 'RAFAEL JOAO MONTEIRO', '14/06/1993', 2),
('74854416988', 45, 'MANOEL JOSE NUNES', '06/04/1977', 3);

SELECT L.IDLINHA AS LINHA, COUNT(PA.IDPASSAGEIRO) AS QTD_PASSAGEIROS
FROM ONIBUS O
INNER JOIN PASSAGEM P
ON O.IDONIBUS = P.ID_ONIBUS
INNER JOIN PASSAGEIRO PA
ON P.IDPASSAGEM = PA.ID_PASSAGEGEM
INNER JOIN LINHA L
ON O.IDONIBUS = L.ID_ONIBUS
GROUP BY L.IDLINHA;

SELECT L.IDLINHA AS LINHA, COUNT(P.IDPASSAGEM) AS QTD_PASSAGENS, SUM(P.VALOR) AS SOMA_TOTAL
FROM ONIBUS O
INNER JOIN PASSAGEM P
ON O.IDONIBUS = P.ID_ONIBUS
INNER JOIN PASSAGEIRO PA
ON P.IDPASSAGEM = PA.ID_PASSAGEGEM
INNER JOIN LINHA L
ON O.IDONIBUS = L.ID_ONIBUS
GROUP BY L.IDLINHA;

CREATE MATERIALIZED VIEW vw_passageiros_por_linha AS
SELECT L.IDLINHA AS LINHA, COUNT(PA.IDPASSAGEIRO) AS QTD_PASSAGEIROS 
FROM ONIBUS O
INNER JOIN PASSAGEM P
ON O.IDONIBUS = P.ID_ONIBUS
INNER JOIN PASSAGEIRO PA
ON P.IDPASSAGEM = PA.ID_PASSAGEGEM
INNER JOIN LINHA L
ON O.IDONIBUS = L.ID_ONIBUS
GROUP BY L.IDLINHA
WITH DATA;

SELECT * FROM vw_passageiros_por_linha;

CREATE MATERIALIZED VIEW vw_soma_total_passagens_por_linha AS
SELECT L.IDLINHA AS LINHA, COUNT(P.IDPASSAGEM) AS QTD_PASSAGENS, SUM(P.VALOR) AS SOMA_TOTAL
FROM ONIBUS O
INNER JOIN PASSAGEM P
ON O.IDONIBUS = P.ID_ONIBUS
INNER JOIN PASSAGEIRO PA
ON P.IDPASSAGEM = PA.ID_PASSAGEGEM
INNER JOIN LINHA L
ON O.IDONIBUS = L.ID_ONIBUS
GROUP BY L.IDLINHA
WITH DATA;

SELECT * FROM vw_soma_total_passagens_por_linha;

CREATE MATERIALIZED VIEW vw_motorista_viagem AS
SELECT V.IDVIAGEM VIAGEM, COUNT(IDMOTORISTA) MOTORISTAS
FROM VIAGEM V 
INNER JOIN MOTORISTA M
ON V.IDVIAGEM = M.ID_VIAGEM
GROUP BY VIAGEM
ORDER BY VIAGEM;

SELECT * FROM vw_motorista_viagem;
