CREATE DATABASE BUSSYS;

USE BUSSYS;

CREATE TABLE ONIBUS(
    IDONIBUS INT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
    PLACA VARCHAR(30) NOT NULL,
    MODELO VARCHAR(30) NOT NULL
);

CREATE TABLE PASSAGEM(
    IDPASSAGEM INT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
    VALOR DOUBLE NOT NULL,
    DATA_COMPRA VARCHAR(30) NOT NULL,
    ID_ONIBUS INT NOT NULL,
    FOREIGN KEY(ID_ONIBUS) REFERENCES ONIBUS(IDONIBUS)
);

CREATE TABLE PASSAGEIRO(
    IDPASSAGEIRO INT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
    NUMERO_CARTAO INT NOT NULL UNIQUE,
    NOME VARCHAR(30) NOT NULL,
    ID_PASSAGEGEM INT NOT NULL,
    FOREIGN KEY(ID_PASSAGEGEM) REFERENCES PASSAGEM(IDPASSAGEM)
);

CREATE TABLE LINHA(
    IDLINHA INT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
    ORIGEM VARCHAR(30) NOT NULL,
    DESTINO VARCHAR(30) NOT NULL,
    ID_ONIBUS INT NOT NULL ,
    FOREIGN KEY (ID_ONIBUS) REFERENCES ONIBUS(IDONIBUS)
);

CREATE TABLE ROTA(
    IDROTA INT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    ID_LINHA INT NOT NULL UNIQUE,
    FOREIGN KEY (ID_LINHA) REFERENCES LINHA(IDLINHA)
);

INSERT INTO ONIBUS VALUES(NULL,"ASD456A","23423FFFFS");
INSERT INTO ONIBUS VALUES(NULL,"SASAS55","435ASFF123");

INSERT INTO PASSAGEM VALUES(NULL,7.9,"28/02/2022", 1);
INSERT INTO PASSAGEM VALUES(NULL,8.5,"01/03/2022", 2);
INSERT INTO PASSAGEM VALUES(NULL,10,"02/03/2022", 1);

INSERT INTO PASSAGEIRO VALUES(NULL, 48948944, "PEDRO", 1);
INSERT INTO PASSAGEIRO VALUES(NULL, 18944256, "RONALDO", 3);
INSERT INTO PASSAGEIRO VALUES(NULL, 95148723, "GABRIEL", 2);

INSERT INTO LINHA VALUES(NULL,"VILA LAURA", "COMÉRCIO", 1);
INSERT INTO LINHA VALUES(NULL,"ITAGARA", "C. DAS ARVORES", 2);

INSERT INTO ROTA VALUES(NULL, "ALIOMAR BALEEIRO", 1);
INSERT INTO ROTA VALUES(NULL, "COMERCIO", 2);

SELECT L.IDLINHA AS LINHA, COUNT(PA.IDPASSAGEIRO) AS QTD_PASSAGEIROS
FROM ONIBUS O
INNER JOIN PASSAGEM P
ON O.IDONIBUS = P.ID_ONIBUS
INNER JOIN PASSAGEIRO PA
ON P.IDPASSAGEM = PA.ID_PASSAGEGEM
INNER JOIN LINHA L
ON O.IDONIBUS = L.ID_ONIBUS
GROUP BY L.IDLINHA;

SELECT L.IDLINHA AS LINHA, COUNT(P.IDPASSAGEM) AS QTD_PASSAGENS, P.VALOR AS VALOR, SUM(P.VALOR) AS SOMA_TOTAL
FROM ONIBUS O
INNER JOIN PASSAGEM P
ON O.IDONIBUS = P.ID_ONIBUS
INNER JOIN PASSAGEIRO PA
ON P.IDPASSAGEM = PA.ID_PASSAGEGEM
INNER JOIN LINHA L
ON O.IDONIBUS = L.ID_ONIBUS
GROUP BY L.IDLINHA;

CREATE MATERIALIZED VIEW viewdemo
SELECT L.IDLINHA AS LINHA, COUNT(PA.IDPASSAGEIRO) AS QTD_PASSAGEIROS 
FROM ONIBUS O
INNER JOIN PASSAGEM P
ON O.IDONIBUS = P.ID_ONIBUS
INNER JOIN PASSAGEIRO PA
ON P.IDPASSAGEM = PA.ID_PASSAGEGEM
INNER JOIN LINHA L
ON O.IDONIBUS = L.ID_ONIBUS
GROUP BY L.IDLINHA
WITH DATA;