-- PGADMIN 4

ALTER TABLE INDICE
ADD COLUMN IDX decimal(8,3);

CREATE PROCEDURE POPULATE_IDX1() 
LANGUAGE SQL 
AS $$ 
    UPDATE INDICE 
    SET IDX =  ( POW(IDH_EDUCACAO,2) * IDH_LONGEVIDADE ) / IDH_GERAL 
$$; 
    
CALL POPULATE_IDX1();

SELECT * FROM INDICE;