 -- t3 sql server

CREATE PROCEDURE POPULATE_IDX
AS
BEGIN
    UPDATE INDICE 
    SET IDX = (POWER(IDH_EDUCACAO,2) * IDH_LONGEVIDADE ) / IDH_GERAL;
END;

CREATE TRIGGER TG_POPULATE_IDX
ON INDICE
FOR UPDATE
AS
BEGIN
    EXECUTE POPULATE_IDX;
END;

UPDATE INDICE SET IDH_GERAL = 0.5 WHERE CODMUNICIPIO = 110001;

SELECT * FROM INDICE;
