CREATE FUNCTION F_POPULATE_IDX() RETURNS TRIGGER 
AS $$
    BEGIN
        UPDATE INDICE SET IDX = (POW(IDH_EDUCACAO,2) * IDH_LONGEVIDADE) / IDH_GERAL;
        RETURN NULL;
    END;
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER TG_SYNC_IDX
AFTER UPDATE 
ON INDICE
FOR EACH ROW
EXECUTE FUNCTION F_POPULATE_IDX();

UPDATE INDICE 
SET IDH_EDUCACAO = 0.955 
WHERE CODMUNICIPIO = 354880;

SELECT * FROM INDICE;
-----------------------------------
CREATE OR REPLACE FUNCTION F_POPULATE_IDX() RETURNS TRIGGER 
AS $$
    BEGIN
        UPDATE INDICE 
        SET IDX = (POW(IDH_EDUCACAO,2) * IDH_LONGEVIDADE) / IDH_GERAL;
        RETURN NULL;
    END;
$$
LANGUAGE PLPGSQL;

CREATE TRIGGER T_SYNC_IDX
AFTER UPDATE ON INDICE FOR EACH ROW
EXECUTE FUNCTION F_POPULATE_IDX();

UPDATE INDICE 
SET IDH_EDUCACAO = 0.955 
WHERE CODMUNICIPIO = 354880;

SELECT * FROM INDICE;

CALL POPULATE_IDX1();

-----------------------------------
select * from indice
WHERE CODMUNICIPIO = 354880;

CREATE OR REPLACE FUNCTION F_POPULATE_IDX() RETURNS TRIGGER 
AS $F_POPULATE_IDX$
    BEGIN
        UPDATE INDICE 
        SET IDX = ((POW(IDH_EDUCACAO,2) * IDH_LONGEVIDADE) / IDH_GERAL);
		RETURN NULL;
    END;
$F_POPULATE_IDX$ LANGUAGE PLPGSQL;

CREATE TRIGGER T_SYNC_IDX
AFTER UPDATE ON INDICE FOR EACH ROW
WHEN (pg_trigger_depth() = 0)
EXECUTE FUNCTION F_POPULATE_IDX();

UPDATE INDICE 
SET IDH_EDUCACAO = 0.955 
WHERE CODMUNICIPIO = 354880 AND ANO = 1991;

ALTER TABLE INDICE
ADD COLUMN IDX decimal(8,3);



